### ISSUE TITLE
Not part of the initial use-cases

### ISSUE THREAD

**Issue by StefanJahnke** [erasmus-without-paper/ewp-specs-api-course-search#1]
It was agreed by the consortium that the course catalogue / course search is not part of the initial EWP functionalities as it is extremely complex and no common way of describing courses exists. The ECTS guidelines give indications on how an ideal course catalogue looks like but isn't sufficient enough to create a standard in EWP that would be very difficult to adhere with for almost all institutions.

**Comment by wrygiel** [comment]
As discussed in Warsaw, we will only include basic Course Catalogue funtionality which would be useful for EWP. We will also document it as such (basic).
